version: "3.8"
services:
  spacecracker:
    build: .
    volumes:
      - ./results:/app/results
      - ./configs:/app/configs
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}